# Copyright (c) 2021 ONGS Inc.
# All rights reserved.
#
# This software may be used, modified, copied, and distributed, in
# both source and binary form provided that the above copyright and
# these terms are retained. Under no circumstances is the author
# responsible for the proper functioning of this software, nor does
# the author assume any responsibility for damages incurred with its
# use.

# author: USER
# first edition: Mon Aug 23 19:31:57 JST 2021
# last modified: DATE
# version: REVISION

include	../mk/win.base.mk
