# Copyright (c) 2002,2021 ONGS Inc.
# All rights reserved.
#
# This software may be used, modified, copied, and distributed, in
# both source and binary form provided that the above copyright and
# these terms are retained. Under no circumstances is the author
# responsible for the proper functioning of this software, nor does
# the author assume any responsibility for damages incurred with its
# use.

# author: USER
# first edition: Mon Sep 15 18:59:43 2003
# last modified: DATE
# version: REVISION

.include "../mk/base.mk"
